[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm_program = "8Wrtbhw9tKyTW7Z1oMyQrhivEoLZCPRxVim1ey9wvTiq"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
